USE SALESDB;
SELECT  FIRSTNAME, LASTNAME FROM CUSTOMERS

INTERSECT

SELECT FIRSTNAME, LASTNAME  FROM EMPLOYEES

INSERT INTO SALESDB.CUSTOMERS VALUE (6,"Jossef","Goldberg","USA", 550 )
INSERT INTO SALESDB.EMPLOYEES VALUE (6,"Jossef","Goldberg","Sales",'1982-02-11',"M",85000,1)

DELETE FROM SALESDB.customers WHERE CUSTOMERID = 6
SELECT * FROM SALESDB.customers;
SELECT * FROM SALESDB.EMPLOYEES;



SELECT * FROM SALESDB.ORDERS
UNION
SELECT * FROM SALESDB.ORDERS_ARCHIVE