# Write your MySQL query statement below
-- SELECT ST.PRODUCT_ID, PT.PRODUCT_NAME,ST.SALE_DATE FROM SALES ST LEFT JOIN PRODUCT PT ON ST.PRODUCT_ID = PT.PRODUCT_ID HAVING ST.SALE_DATE >="2019-01-01" AND ST.SALE_DATE<="2019-03-31"


SELECT PT.PRODUCT_NAME, PT.PRODUCT_ID FROM PRODUCT PT JOIN 
(SELECT ST.PRODUCT_ID FROM SALES ST GROUP BY ST.PRODUCT_ID HAVING MIN(ST.SALE_DATE)>="2019-01-01" AND MAX(ST.SALE_DATE)<="2019-03-31" ) ST1 ON PT.PRODUCT_ID = ST1.PRODUCT_ID



