# Write your MySQL query statement below








SELECT ST.STUDENT_ID AS student_id, ST.STUDENT_NAME as student_name,  SUBT.SUBJECT_NAME as subject_name, IFNULL(COUNT(ET.SUBJECT_NAME),0) as attended_exams FROM STUDENTS ST 
CROSS JOIN SUBJECTS SUBT 
LEFT JOIN EXAMINATIONS ET ON SUBT.SUBJECT_NAME = ET.SUBJECT_NAME AND ST.STUDENT_ID = ET.STUDENT_ID
GROUP BY ST.STUDENT_ID,ST.STUDENT_NAME, SUBT.SUBJECT_NAME 
ORDER BY ST.STUDENT_ID , ST.STUDENT_NAME


