
# Write your MySQL query statement below
SELECT PT.PRODUCT_NAME as product_name,SUM(OT.UNIT) as unit FROM ORDERS OT 
JOIN PRODUCTS PT ON OT.PRODUCT_ID = PT.PRODUCT_ID  
WHERE OT.ORDER_DATE >="2020-02-01" AND OT.ORDER_DATE <="2020-02-29"
GROUP BY OT.PRODUCT_ID 
HAVING unit>=100
