# Write your MySQL query statement below
SELECT SELL_DATE AS sell_date , COUNT(DISTINCT(PRODUCT)) as num_sold, GROUP_CONCAT(DISTINCT(PRODUCT) ORDER BY PRODUCT) as products FROM ACTIVITIES A1 
GROUP BY SELL_DATE 