# Write your MySQL query statement below
SELECT 
V.CUSTOMER_ID AS customer_id, 
-- SUM(IF (T.TRANSACTION_ID IS NULL, 1,0)) AS count_no_trans 
COUNT(V.CUSTOMER_ID) AS count_no_trans
FROM VISITS V LEFT JOIN TRANSACTIONS T ON V.VISIT_ID = T.VISIT_ID 
WHERE T.TRANSACTION_ID IS NULL 
GROUP BY V.CUSTOMER_ID


