# Write your MySQL query statement below

SELECT  RT.CONTEST_ID AS contest_id, ROUND(COUNT(UT2.USER_ID)*100.0/ UT2.COU,2) AS percentage
    FROM REGISTER RT LEFT JOIN (
   SELECT UT1.USER_ID, C.COU FROM USERS UT1 CROSS JOIN (SELECT COUNT(DISTINCT(UT2.USER_ID)) AS COU FROM USERS UT2 ) C) UT2
    ON RT.USER_ID = UT2.USER_ID GROUP BY RT.CONTEST_ID
    ORDER BY percentage DESC, contest_id ;

