# Write your MySQL query statement below



SELECT AST.MACHINE_ID as machine_id, ROUND(SUM(AEN.TIMESTAMP-AST.TIMESTAMP)/COUNT(AST.PROCESS_ID),3) as processing_time
FROM ACTIVITY AST INNER JOIN ACTIVITY  AEN ON AST.MACHINE_ID = AEN.MACHINE_ID and AST.PROCESS_ID = AEN.PROCESS_ID 
WHERE AST.ACTIVITY_TYPE = 'start' and AEN.ACTIVITY_TYPE = 'end' 
GROUP BY AST.MACHINE_ID