-- # Write your MySQL query statement below
-- SELECT S.NAME AS name FROM SALESPERSON S JOIN (SELECT C.COM_ID,C.NAME ,O.SALES_ID FROM COMPANY C JOIN ORDERS O ON C.COM_ID=O.COM_ID) AS T1 ON S.SALES_ID = T1.SALES_ID WHERE T1.NAME !="RED"

SELECT S.NAME FROM 
SALESPERSON S 
LEFT JOIN ORDERS O ON S.SALES_ID = O.SALES_ID
LEFT JOIN COMPANY C ON O.COM_ID = C.COM_ID
GROUP BY S.NAME   HAVING FIND_IN_SET("RED",GROUP_CONCAT(C.name)) =0  OR  GROUP_CONCAT(C.NAME) IS NULL

-- WHERE C.NAME !='RED'


-- GROUP BY S.NAME
-- , GROUP_CONCAT(C.NAME)

