/*
Enter your query here.
*/

-- SELECT * FROM SUBMISSIONS


SELECT H.HACKER_ID, MAX(H.NAME), SUM(ST.SCORE) AS TOTSCORE FROM HACKERS H JOIN
-- GIVES ME MAX SCORE/HACKER_ID/CHALLENGE_ID, COLS - HACKER_ID, SCORE
(SELECT S.HACKER_ID AS HACKER_ID, MAX(S.SCORE) AS SCORE FROM
SUBMISSIONS S GROUP BY S.HACKER_ID, S.CHALLENGE_ID ) ST 

ON H.HACKER_ID = ST.HACKER_ID
GROUP BY H.HACKER_ID HAVING TOTSCORE>0 
ORDER BY TOTSCORE DESC, H.HACKER_ID